export const ENDPOINTS = {
    CATEGOREIS:{
        LIST:'/categories',
        CREATE:'/categories',
        UPDATE:'/categories/:categoryId',
        DELETE:'/categories/:categoryId',
    },
    PRODUCTS:{
        LIST:'/products',
        CREATE:'/products',
        UPDATE:'/products/:productId',
        DELETE:'/products/:productId',
    },
    ORDERS:{
        LIST:'/orders',
        CREATE:'/orders',
        UPDATE:'/orders/:orderId',
        DELETE:'/orders/:orderId',
    }
}